### ISSUE TITLE
Support performance testing of external environments

### ISSUE THREAD

**Issue by akira** [performanceci/performanceci-core#36]
As a perfci user, I should be able to use projects that deployed externally and not within perfci. I should be able to trigger a build via a webhook and see build results.

## Acceptance Criteria

- be able to configure external projects
- test is run against an external base URL
- webhook that supports build of project

## Sub-Tasks

- [x] #37 | UI support to configure an external project
- [x] #38 | Backend to skip git checkout / docker builds and test 
- [x] #39 | Provide webhook to trigger builds when new version is deployed

**Comment by akira** [comment]
Works for me :+1:
